[[Go]]
## Основы обработки ошибок
В Go ошибка возвращается из функции последним значением. **ЭТО ОЧЕНЬ СТРОГОЕ СОГЛАШЕНИЕ**. 
Сообщение об ошибке начинаются с маленькой буквы и не содержат в конце знаки препинания. 
Тип `error` - это интерфейс с одним методом `Error() string`. Любой тип удовлетворяющий этому интерфейсу будет считаться ошибкой.

Причины, почему в Go ошибки, а не исключения:
- По сигнатуре функции можно понять, может ли быть ошибка или нет;
- Так как обработка ошибок снабжается отступом, а логика - нет, то сразу видно, где что.

Тут еще прикольный момент есть - автор пишет, что в Go важна частота и ясность кода и вот буквально на этой же странице приведена функция `doubleEven` с параметром `i` - очень чисто и ясно - красава.

## Используйте строки в случае простых ошибок
В стандартной библиотеке есть 2 способа создать ошибку со своим текстом - `fmt.Errorf` и `errors.New`
```go
func div(divident, divisor int) (int, error) {
    if divisor == 0 {
        return 0, fmt.Errorf("divisor cant be equal to zero. Divizor = %d", divisor)
    }
    return divident / divisor, nil
}
```
`fmt.Errorf` позволяет форматировать текст ошибки.
Ошибка через `errors.New`
```go
func div(divident, divisor int) (int, error) {
    if divisor == 0 {
        return 0, errors.New("divisor cant be equal to zero")
    }
    return divident / divisor, nil
}
```

## Сигнальные ошибки (sentinel errors)
Насколько я понял - сигнальные ошибки, это что-то вроде именованных ошибок. Например, в пакете `archive/zip` есть сигнальная ошибка `ErrFormat`. Она объявлена так:
```go
var ErrFormat = errors.New("text")
```
И потом ее можно просто возвращать и проверять, что это в функция вернула именно ошибку `ErrFormat`
```go
if err == zip.ErrFormat {
	// handle
}
```
Используя сигнальные ошибки надо будет сделать их доступными и поддерживаемыми во всех пакетах и релизах. То есть нужно несколько раз подумать - а надо ли оно? Сигнальная ошибка хороша в случаях, когда она сигнализирует о состоянии, при котором невозможно продолжить обработку и когда нам не нужна контекстная информация. Это тоже не очень понял, вот что значит "невозможно продолжить обработку". Примеры он не привел, когда лучше использовать сигнальную ошибку, а когда можно обойтись `errors.New`.

Также Дейв Чейни (крутой дядька в Go) предложил использовать константные ошибки:
```go
package consterr

type Sentinel string

func (s Sentinel) Error() string {
	return string(s)
}

-- new package --

package mypkg

const (
	ErrFoo = consterr.Sentinel("foo err")
	ErrBar = consterr.Sentinel("bar err")
)
```
Но Боднер пишет, что это не идиоматично, так как две ошибки могут быть равны друг другу, если будут равны их строки в сообщении. Ошибка `errors.New` всегда будет равна только самой себе или переменным, куда ее явно положили. В общем так не надо делать. Да и сигнальные ошибки тоже не надо.

## Errros are values
Можно расширить базовые ошибки, использовав структуру
```go
type StatusErr struct {
    message string
}

func (s StatusErr) Error() string {
    return s.message
}

func div(divident, divisor int) (int, error) {
    if divisor == 0 {
        return 0, StatusErr{message: "aboba"}
    }
    return divident / divisor, nil
}
```
Например, для журналирования. В эту структуру можно добавить еще много информации.

При использовании своего типа ошибок нельзя допускать, чтобы функция возвращала ее неинициализированной
```go
func GenerateError(flag bool) error {
    var genErr StatusErr
    if !flag {
        genErr = StatusErr{"aboba"}
    }
    return genErr
}
  
func main() {
    err := GenerateError(true)
    fmt.Println(err != nil) // true
    err = GenerateError(false)
    fmt.Println(err != nil) // true
}
```
Так происходит, потому что базовый тип не равен `nil`, так как тип `error` это интерфейс, а интерфейс равен nil, когда базовый тип и базовое значение равны `nil`

Решить эту проблему можно 2мя способами:
Первый - возвращать явно `nil`, если ошибки не произошло
```go
func GenerateError(flag bool) error {
    var genErr StatusErr
    if !flag {
        genErr = StatusErr{"aboba"}
    }
    return nil
}
```
Второй - давать тип не собственный, а `error`
```go
func GenerateError(flag bool) error {
    var genErr error
    if !flag {
        genErr = StatusErr{"aboba"}
    }
    return genErr
}
```
Предпочтительнее второй, так как определять ошибки с пользовательским типом, а не `error` - не очень хороший вариант
## Обертывание ошибок
Когда ошибка передается в коде, в нее часто нужно вносить доп. инфу. Если доп. инфа добавляется в новую ошибку - это называется **обёртывание** ошибки. Несколько подряд идущих ошибок образую цепочку ошибок.

Функция `fmt.Errorf` позволяет обернуть ошибку, использовав в ней глагол `%w`. Принято добавлять текст обернутой ошибки после `:`
Также можно извлечь обернутую ошибку с помощью функции `errros.Unwrap`. Если в ошибке нет обернутой ошибки, то вернется `nil`. 
```go
import (
    "errors"
    "fmt"
    "os"
)


func OpenFile(fileName string) error {
    f, err := os.Open(fileName)
    if err != nil {
        return fmt.Errorf("in OpenFile: %w", err)
    }
    f.Close()
    return nil
}

func main() {
    err := OpenFile("aboba.txt")
    if err != nil {
        fmt.Println(err)
        if wrapedErr := errors.Unwrap(err); wrapedErr != nil {
            fmt.Println(wrapedErr)
        }
    }
}
```
На экран выведется:
```
in OpenFile: open aboba.txt: no such file or directory 
open aboba.txt: no such file or directory 
```

Если нам нужно реализовать оборачивание ошибки в пользовательском типе, то нужно создать у него метод `Unwrap`
```go
import (
    "errors"
    "fmt"
    "os"
)

type ErrMy struct {
    message string
    err     error
}

func (em ErrMy) Error() string {
    return em.message
}

func (em ErrMy) Unwrap() error {
    return em.err
}

func OpenFile(fileName string) error {
    f, err := os.Open(fileName)
    if err != nil {
        return ErrMy{
            message: fmt.Sprintf("file %s not found: %v", fileName, err),
            err:     err,
        }
    }
    f.Close()
    return nil
}

func main() {
    err := OpenFile("aboba.txt")
    if err != nil {
        fmt.Println(err)
        if wrapedErr := errors.Unwrap(err); wrapedErr != nil {
            fmt.Println(wrapedErr)
        }
    }
}
```
```
file aboba.txt not found: open aboba.txt: no such file or directory
open aboba.txt: no such file or directory
```
Если нам нужен просто текст ошибки, без оборачивания, нужно использовать глагол `%v`

## Функции `Is` и `As`
### `Is`
Нельзя проверить наличие какой-то ошибки с помощью `==`. Также не получится это сделать с помощью type assertion и type switcher. Для этого нужно использовать функцию `errors.Is` для того, чтобы узнать, если ли сигнальная ошибка в цепочке ошибок.
```go
func main() {
    err := OpenFile("aboba.txt")
    if err != nil {
        fmt.Println(err)
        if errors.Is(err, os.ErrNotExist) {
            fmt.Println("Does not exist")
        }
    }
}
```
Мы проверяем, нет ли в возвращаемой ошибке сигнальной ошибки ErrNotExist. Функция проходит по цепочке и сравниваем каждую ошибку с целевой через `==`. Если это не подходит, можно реализовать метод `Is` в пользовательской ошибке.

### `As`
С помощью `errors.As` можно узнать, не совпадает ли одна из ошибок в цепочке с переданным типом.
```go
err := Foo()
var myErr myErr

if errors.As(err, &myErr) {
	//
}
```
Также можно указывать интерфейс:
```go
var coder interface {
	Code()
}

err := Foo()

if errors.As(err, &coder) {

}
```

## Обертывание ошибок с помощью `defer`
Иногда нужно вернуть одну и ту же ошибку в нескольких случаях:
```go
func DoSmth(val1 int, val2 string) (string, error) {
    val3, err := doThing(val1)
    if err != nil {
        return "", fmt.Errorf("in DoSmth: %w", err)
    }
    val4, err := doThing2(val2)
    if err != nil {
        return "", fmt.Errorf("in DoSmth: %w", err)
    }
    return "qwe", nil
}
```
Такой код можно упросить с помощью `defer`
```go
func DoSmth(val1 int, val2 string) (_ string, err error) {
    defer func() {
        if err != nil {
            err = fmt.Errorf("in DoSmth: %w", err)
        }
    }
    val3, err := doThing(val1)
    if err != nil {
        return "", err
    }
    val4, err := doThing2(val2)
    if err != nil {
        return "", err
    }
    return "qwe", nil
}
```
Только нужно присвоить имена возвращаемым значениям.

## Функции `panic` и `recover`
Паника в Go возникает, когда среда не знает что ей делать. Например, кончилась память, деление на 0 и тд. В общем ПрЕкОлЫ.
При срабатывании паники функция, в которой она сработала завершается и запускаются отложенные функции, привязанные к вызывающей и так пока не дойдет до функции `main`. Чтобы вызвать панику, нужно вызвать одноименную функцию и передать туда что угодно
```go
func doPanic(s string) {
    panic(s)
}

func main() {
    doPanic("asd")
}
```
```go
panic: asd

goroutine 1 [running]:
main.doPanic(...)
        /home/nikita/code/go_code/main.go:4
main.main()
        /home/nikita/code/go_code/main.go:8 +0x34
exit status 2
```
При панике видна трассировка стека. 
Панику можно перехватить с помощью функции `recover`. 
```go
func doPanic(s int) {
    defer func() {
        if isPanic := recover(); isPanic != nil {
            fmt.Println("Перехватил панику")
        }
    }()
    if s == 0 {
        panic(s)
    }
    fmt.Println(s)
}
func main() {
    for _, v := range []int{1, 0, 3} {
        doPanic(v)
    }
}
```
```
1
Перехватил панику
3
```
Функция `recover` должна быть только в `defer`, так как при панике выполняются только отложенные функции.