[[Go]]
## `errcheck`
Эта утилита проверяет, в каком месте возвращается ошибка, но не присваивается переменной
```shell
 ~/code/learn_go_with_tests/errors/ errcheck .
wallet_test.go:33:18:   wallet.Withdraw(Bitcoin(10))
```
Означает, что на 33 строчке функция возвращает ошибку, но она не кладется в переменную. Что-то вроде:
```go
func f() err {
	return errors.New("error")
}

f()
```
