[[100 ошибок в Go и как их избежать]]

Рассмотрим пример, когда функция открывает группу файлов, полученных их канала:
```go
func readFiles(ch <- chan string) error {
	for path := range ch {
		file, err := os.Open(path)
		if err != nil {
			return err
		}
		defer file.Close()
	}
}
```
В такой реализации проблема в том, что `defer` планирует вызов функции, когда возвращается окружающая функция. То есть когда вернется значение в `readFiles`. Если она не вернет значение - файлы останутся открытыми.
Решить проблему можно, реализовав функцию-обертку, в которой будет `defer`
```go
func readFiles(ch <- chan string) error {
	for path := range ch {
		if err := readFile(path); err != nil {
			return err
		}
	}
	return nil
}

func readFile(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()
}
```
Другой подход в том, чтобы сделать функцию `readFile` закрывающей
```go
func readFiles(ch <- chan string) error {
	for path := range ch {
		err := func() error {
			// ...
			defer file.Close()
			// ...
		}()
		if err != nil {
			return err
		}
	}
	return nil
}
```

Важно помнить о том, что `defer` складывается на стек, а не выполняется после каждой итерации. Если цикл не завершится, это может привести к утечки памяти.