[[100 ошибок в Go и как их избежать]]

Пакет `errgroup` экспортирует функцию `WithContext`, которая возвращает `*Group`. У нее есть 2 метода:
- `Go`, чтобы запустить вызов в новой горутине
- `Wait`, чтобы заблокировать выполнение, пока все горутины не будут завершены. Он возвращает первую ненулевую ошибку.

```go
func handler(ctx context.Context, circles []Circle) ([]Result, error) {
	results := make([]Result, len(circles))
	g, ctx := errgroup.WithContext(ctx)
	for i, c := range circles {
		g.Go(func() {
			res, err := foo(ctx, circle)
			if err != nil {
				return err
			}
			results[i] = res
			return nil 
		})
		if err := g.Wait(); err != nil {
			return nil, err
		}
		return results, nil
	}
}
```
Важно помнить, что процесс в `g.Go` должен быть контекстно зависимым. Иначе не будет никакого эффекта.
В коде выше мы на каждой итерации вызываем процесс через `g.Go`. Затем в `g.Wait()` ждем завершения всех горутин
У errgroup есть еще одно преимущество. Например у нас есть 3 пар-ых вызова:
- 1 возвращает ошибку через 1 мс
- 2 и 3 вызовы возвращают результат или ошибку через 5мс
Нам нет смысла ждать завершения 2 и 3 вызов. Использование `errgroup.WithContext` создает общий контекст. Так как первый вызов завершается раньше всех, он отменит общий контекст.

Когда нужно запустить несколько горутин И обрабатывать ошибки, а также передавать контекст, стоит подумать об `errgroup`

